---
abstract: "Locate sequences within HIV using LANL's web tool"
author:
  - 'Thomas Sibley <trsibley@uw.edu>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-WebService-LANL-SequenceLocator
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
optional_features:
  server:
    description: 'Web API server'
    requires:
      File::Share: 0
      JSON: 0
      JSON::XS: 0
      Plack::App::File: 0
      Plack::Middleware::ReverseProxy: 0
      Server::Starter: 0
      Starlet: 0
      Web::Simple: 0
requires:
  HTML::LinkExtor: 0
  HTML::TableExtract: 0
  HTML::TokeParser: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  List::AllUtils: 0
  Moo: 0
  perl: 5.018
  strictures: 0
resources:
  bugtracker: https://github.com/MullinsLab/Bio-WebService-LANL-SequenceLocator/issues
  homepage: http://indra.mullins.microbiol.washington.edu/locate-sequence/
  repository: https://github.com/MullinsLab/Bio-WebService-LANL-SequenceLocator.git
version: 20140328
